[versions]
agp = "8.2.2"
kotlin = "1.9.0"
core-ktx = "1.12.0"
appcompat = "1.6.1"
compose-bom = "2023.08.00"
tv-foundation = "1.0.0-alpha07"
tv-material = "1.0.0-alpha07"
lifecycle-runtime-ktx = "2.7.0"
activity-compose = "1.8.2"
hilt-navigation-compose = "1.1.0"
hilt-android = "2.48.1"
kotlin-android = "1.9.0"
kotlinx-serialization = "1.6.0"
ksp = "1.9.0-1.0.13"
kotlinx-coroutines = "1.6.0"
navigation-compose = "2.7.6"
core-splashscreen = "1.0.1"
benchmark-macro-junit4 = "1.2.2"
coil-compose = "2.5.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "tv-foundation" }
tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tv-material" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-android" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

